import React, { useEffect, useMemo, useState } from 'react';
import {
  collection,
  doc,
  getDocs,
  serverTimestamp,
  writeBatch,
} from 'firebase/firestore';
import { UserRoundCheck, Users, X } from 'lucide-react';
import { db } from '../firebase'; // Update path if needed

const LEAVE_FIELDS = [
  { key: 'plannedLeave', label: 'Planned Leave' },
  { key: 'sickLeave', label: 'Sick Leave' },
  { key: 'casualLeave', label: 'Casual Leave' },
  { key: 'specialLeave', label: 'Special Leave' },
  { key: 'workFromHome', label: 'Work From Home' },
  { key: 'lossOfPay', label: 'Loss of Pay' },
];

const createEmptyCounts = () => ({
  plannedLeave: 0,
  sickLeave: 0,
  casualLeave: 0,
  specialLeave: 0,
  workFromHome: 0,
  lossOfPay: 0,
});

/**
 * Converts:
 * abc@gmail.com
 *
 * Into:
 * abc@gmail_com
 */
export const leaveDocumentId = (email = '') =>
  email.trim().toLowerCase().replace(/\./g, '_');

export default function LeaveBalanceEditorModal({
  isOpen,
  onClose,
  currentUserEmail,
}) {
  const [scope, setScope] = useState('all');
  const [users, setUsers] = useState([]);
  const [selectedEmails, setSelectedEmails] = useState([]);
  const [counts, setCounts] = useState(createEmptyCounts);
  const [loadingUsers, setLoadingUsers] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!isOpen) return;

    const loadUsers = async () => {
      try {
        setLoadingUsers(true);
        setError('');

        /*
          Assumes the following Firestore collection:

          users/{userDocumentId}

          Each user document should contain:
          {
            email: "abc@gmail.com",
            name: "ABC"
          }
        */
        const snapshot = await getDocs(collection(db, 'users'));

        const userList = snapshot.docs
          .map((userDocument) => {
            const data = userDocument.data();

            return {
              id: userDocument.id,
              email: data.email?.trim() || '',
              name: data.name || data.displayName || '',
            };
          })
          .filter((user) => user.email);

        setUsers(userList);
      } catch (err) {
        console.error('Error loading users:', err);
        setError('Unable to load users. Please try again.');
      } finally {
        setLoadingUsers(false);
      }
    };

    loadUsers();
  }, [isOpen]);

  const selectedUserCount = useMemo(() => {
    return scope === 'all' ? users.length : selectedEmails.length;
  }, [scope, users.length, selectedEmails.length]);

  if (!isOpen) return null;

  const toggleUser = (email) => {
    setSelectedEmails((previousEmails) => {
      if (previousEmails.includes(email)) {
        return previousEmails.filter(
          (selectedEmail) => selectedEmail !== email
        );
      }

      return [...previousEmails, email];
    });
  };

  const updateCount = (key, value) => {
    const numericValue = Math.max(0, Number(value) || 0);

    setCounts((previousCounts) => ({
      ...previousCounts,
      [key]: numericValue,
    }));
  };

  const resetForm = () => {
    setScope('all');
    setSelectedEmails([]);
    setCounts(createEmptyCounts());
    setError('');
  };

  const handleCancel = () => {
    if (saving) return;

    resetForm();
    onClose();
  };

  const handleSave = async () => {
    const hasAtLeastOneLeaveValue = Object.values(counts).some(
      (value) => Number(value) > 0
    );

    if (!hasAtLeastOneLeaveValue) {
      setError('Please enter at least one leave count greater than 0.');
      return;
    }

    const targetEmails =
      scope === 'all'
        ? users.map((user) => user.email)
        : selectedEmails;

    if (!targetEmails.length) {
      setError('Please select at least one user.');
      return;
    }

    try {
      setSaving(true);
      setError('');

      /*
        Firestore structure created for each user:

        leave/{emailDocumentId}/balance/{autoGeneratedDocumentId}

        Example:

        leave/abc@gmail_com/balance/AbCdEf123456
      */

      /*
        A Firestore batch supports up to 500 writes.
        This code uses 450 writes per batch as a safety margin.
        Each selected user produces one write.
      */
      const batchSize = 450;

      for (
        let startIndex = 0;
        startIndex < targetEmails.length;
        startIndex += batchSize
      ) {
        const emailChunk = targetEmails.slice(
          startIndex,
          startIndex + batchSize
        );

        const batch = writeBatch(db);

        emailChunk.forEach((email) => {
          /*
            Reference to:

            leave/{emailDocumentId}/balance
          */
          const balanceCollectionRef = collection(
            db,
            'leave',
            leaveDocumentId(email),
            'balance'
          );

          /*
            Calling doc() without an ID creates a document reference
            with an automatically generated Firestore ID.
          */
          const balanceDocumentRef = doc(balanceCollectionRef);

          batch.set(balanceDocumentRef, {
            email,
            plannedLeave: Number(counts.plannedLeave) || 0,
            sickLeave: Number(counts.sickLeave) || 0,
            casualLeave: Number(counts.casualLeave) || 0,
            specialLeave: Number(counts.specialLeave) || 0,
            workFromHome: Number(counts.workFromHome) || 0,
            lossOfPay: Number(counts.lossOfPay) || 0,
            updatedBy: currentUserEmail || '',
            updatedAt: serverTimestamp(),
          });
        });

        await batch.commit();
      }

      resetForm();
      onClose();
    } catch (err) {
      console.error('Error saving leave balances:', err);
      setError('Could not save leave balances. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4 backdrop-blur-[2px]"
      onClick={(event) => {
        if (event.target === event.currentTarget) {
          handleCancel();
        }
      }}
    >
      <div className="w-full max-w-2xl rounded-2xl border border-slate-100 bg-white p-5 shadow-xl sm:p-6">
        <div className="mb-5 flex items-start justify-between gap-4">
          <div>
            <h3 className="text-base font-bold text-slate-800">
              Edit Leave Balance
            </h3>

            <p className="mt-1 text-xs text-slate-400">
              Add leave counts for all employees or selected employees.
            </p>
          </div>

          <button
            type="button"
            onClick={handleCancel}
            disabled={saving}
            className="text-slate-400 transition-colors hover:text-slate-700 disabled:cursor-not-allowed disabled:opacity-50"
            aria-label="Close"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="mb-5 grid grid-cols-1 gap-3 sm:grid-cols-2">
          <button
            type="button"
            onClick={() => {
              setScope('all');
              setError('');
            }}
            disabled={saving}
            className={`flex items-center gap-3 rounded-xl border p-3 text-left transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${
              scope === 'all'
                ? 'border-blue-300 bg-blue-50'
                : 'border-slate-200 hover:bg-slate-50'
            }`}
          >
            <Users
              className={`h-5 w-5 ${
                scope === 'all' ? 'text-blue-600' : 'text-slate-400'
              }`}
            />

            <div>
              <p className="text-sm font-semibold text-slate-700">
                All Users
              </p>

              <p className="text-[11px] text-slate-400">
                Apply leave counts to every user.
              </p>
            </div>
          </button>

          <button
            type="button"
            onClick={() => {
              setScope('custom');
              setError('');
            }}
            disabled={saving}
            className={`flex items-center gap-3 rounded-xl border p-3 text-left transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${
              scope === 'custom'
                ? 'border-blue-300 bg-blue-50'
                : 'border-slate-200 hover:bg-slate-50'
            }`}
          >
            <UserRoundCheck
              className={`h-5 w-5 ${
                scope === 'custom' ? 'text-blue-600' : 'text-slate-400'
              }`}
            />

            <div>
              <p className="text-sm font-semibold text-slate-700">
                Custom Users
              </p>

              <p className="text-[11px] text-slate-400">
                Choose specific employees.
              </p>
            </div>
          </button>
        </div>

        {scope === 'custom' && (
          <div className="mb-5">
            <p className="mb-2 text-xs font-semibold text-slate-600">
              Select users
            </p>

            <div className="max-h-44 overflow-y-auto rounded-xl border border-slate-200">
              {loadingUsers ? (
                <p className="p-4 text-center text-xs text-slate-400">
                  Loading users…
                </p>
              ) : users.length === 0 ? (
                <p className="p-4 text-center text-xs text-slate-400">
                  No users found in the <code>users</code> collection.
                </p>
              ) : (
                users.map((user) => (
                  <label
                    key={user.id}
                    className="flex cursor-pointer items-center gap-3 border-b border-slate-100 px-4 py-3 last:border-0 hover:bg-slate-50"
                  >
                    <input
                      type="checkbox"
                      checked={selectedEmails.includes(user.email)}
                      onChange={() => toggleUser(user.email)}
                      disabled={saving}
                      className="h-4 w-4 accent-blue-600 disabled:cursor-not-allowed"
                    />

                    <div>
                      <p className="text-xs font-semibold text-slate-700">
                        {user.name || 'Unnamed User'}
                      </p>

                      <p className="text-[11px] text-slate-400">
                        {user.email}
                      </p>
                    </div>
                  </label>
                ))
              )}
            </div>
          </div>
        )}

        <div className="mb-4">
          <p className="mb-3 text-xs font-semibold text-slate-600">
            Add leave count
          </p>

          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
            {LEAVE_FIELDS.map((field) => (
              <label key={field.key}>
                <span className="mb-1.5 block text-xs font-medium text-slate-500">
                  {field.label}
                </span>

                <input
                  type="number"
                  min="0"
                  step="1"
                  value={counts[field.key]}
                  onChange={(event) =>
                    updateCount(field.key, event.target.value)
                  }
                  disabled={saving}
                  className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-800 outline-none transition-all focus:border-blue-400 focus:ring-2 focus:ring-blue-50 disabled:cursor-not-allowed disabled:bg-slate-50 disabled:opacity-70"
                />
              </label>
            ))}
          </div>
        </div>

        <p className="mb-4 text-[11px] text-slate-400">
          This will be applied to <b>{selectedUserCount}</b> user
          {selectedUserCount === 1 ? '' : 's'}.
        </p>

        {error && (
          <div className="mb-4 rounded-lg border border-red-100 bg-red-50 px-3 py-2 text-xs text-red-600">
            {error}
          </div>
        )}

        <div className="flex justify-end gap-2 border-t border-slate-100 pt-4">
          <button
            type="button"
            onClick={handleCancel}
            disabled={saving}
            className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-500 transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
          >
            Cancel
          </button>

          <button
            type="button"
            onClick={handleSave}
            disabled={saving || loadingUsers}
            className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {saving ? 'Saving…' : 'Save Leave Balance'}
          </button>
        </div>
      </div>
    </div>
  );
}